### ISSUE TITLE
Requesting compatibility with EnhancedCelestials' lunar events

### ISSUE THREAD

**Issue by Moofellow** [TheComputerizer/Music-Triggers#1]
Link to mod: [https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials](url)

For full compatibility:
Integrate support for EC's Blood Moon in the "bloodmoon" trigger
Integrate support for EC's Harvest Moon in the "harvestmoon" trigger
Add a new trigger, "bluemoon", for EC's Blue Moon

IIRC, EC already has a system for lunar event ambience. A quick dig through the mod repo should be all that's needed to find it. Good luck mate.

**Comment by TheComputerizer** [comment]
I had forgotten to update the curseforge website, but if you look in the config for the 1.16 version, enhanced celestials already has support with those 3 triggers
