### ISSUE TITLE
Music Fade affects Dynamic Surroundings ambient sound loops

### ISSUE THREAD

**Issue by zaeonNineZero** [TheComputerizer/Music-Triggers#10]
As the title indicates, whenever music tracks fade out, the 'fade out' effect also affects the volume of ambient biome sounds from the Dynamic Surroundings mod.  This probably has something to do with Dynamic Surroundings using streamed audio for its biome sound loops.

**Comment by TheComputerizer** [comment]
This is semi-intentional, as the fade makes all sounds fade. I was planning on switching the music player so it only stops/fades sounds played from the mod for 5.0 though. This is not an issue with dynamic surroundings
