### ISSUE TITLE
Height trigger plays on all y levels when check_above_level is true (v6.1 forge, Minecraft 1.18.2)

### ISSUE THREAD

**Issue by LuckyChickens** [TheComputerizer/Music-Triggers#101]
Whenever the check_above_level parameter is set to true in a height trigger, the trigger is always active even when I am well below the y level that it should be activating at (the "sky" trigger is the one causing issues).

    [triggers]

	[triggers.dimension]
		identifier = "nether"
		resource_name = [ "nether" ]
		fade_in = "10"
		fade_out = "10"
		priority = "10"

	[[triggers.height]]
		identifier = "sky"
		fade_in = "10"
		fade_out = "10"
		level = "90"
		check_for_sky = false
		check_above_level = true
		priority = "9"

	[[triggers.height]]
		identifier = "cave"
		fade_in = "10"
		fade_out = "10"
		level = "40"
		priority = "9"

	[triggers.generic]
	[triggers.menu]
	[triggers.loading]

**Comment by TheComputerizer** [comment]
Do any of those triggers not have songs attached to them? It might be a different issue entirely where the channels thread crashes so the debug info doesnt get updated anymore

**Comment by LuckyChickens** [comment]
Loading is the only trigger without any songs using it. Otherwise, every trigger seen above has at least one song using it.

**Comment by TheComputerizer** [comment]
This has been fixed in 6.2
