### ISSUE TITLE
[1.19.2] Server crash on startup (Forge: 43.1.57)

### ISSUE THREAD

**Issue by EPKGames** [TheComputerizer/Music-Triggers#102]
**Describe the bug**
Forge servers crashes on startup.
`Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Options for invalid dist DEDICATED_SERVER`

**To Reproduce**
start Forge server version: 43.1.57

**Additional context**
[crash-2023-04-01_17.29.45-fml.txt](https://github.com/TheComputerizer/Music-Triggers/files/11129918/crash-2023-04-01_17.29.45-fml.txt)

**Comment by EPKGames** [comment]
Are there any updates on this? apparently it also does not work with newer forge versions: forge-1.19.2-43.2.0

**Comment by TheComputerizer** [comment]
This has been fixed in 6.2
