### ISSUE TITLE
[1.19.2-6.1] Delete Mode doesn't work

### ISSUE THREAD

**Issue by Sketiq** [TheComputerizer/Music-Triggers#104]
**Describe the bug**
Delete mode in channel tab doesn't work, and there's no slider to slide through channels

**Comment by TheComputerizer** [comment]
What do you mean about doesn't work? Does it not turn red, do the channels not get deleted, or are you trying to delete something that can't be deleted.

Also what do you mean about a slider?

**Comment by Sketiq** [comment]
Delete Mode doesn't turn red here so I can't delete anything, but it works in other tabs such as Triggers, Songs etc...
![image](https://user-images.githubusercontent.com/129682530/229588382-f621e077-1fe1-450e-b37e-d6ea8bb9d3d2.png)

And about the slider I mean I can't choose some channels that are on bottom, look:
![image](https://user-images.githubusercontent.com/129682530/229589248-dc0fbe14-52b3-49c8-a941-b79c761641fa.png)

**Comment by TheComputerizer** [comment]
Oh another GUI scaling issue. Yeah I can add a scroll bar to that screen

**Comment by TheComputerizer** [comment]
This has been fixed in 6.2
