### ISSUE TITLE
[1.19.2-6.1] Constantly Crashing

### ISSUE THREAD

**Issue by Aabaddon** [TheComputerizer/Music-Triggers#106]
**Describe the bug**
When i try to use this mod it just instantly crashes.

**To Reproduce**
Try to set any trigger.

**Additional context**
I removed every other sound mod (like ambient sound 5) because they made this one crash on startup, i could finally load this mod in the game and when i tried to set a trigger it just crashed, i tried changing the song for a shorter one but it still keeps crashing.

**Comment by TheComputerizer** [comment]
I can't fix the issue if you don't provide a crash report and/or log from when you crashed.

**Comment by TheComputerizer** [comment]
Whatever the issue was, there were quite a few crashes and related issues fixed in 6.2, so it may have been resolved. If it was not feel free to open a separate issue
