### ISSUE TITLE
[1.18.2 6.1] Play Once not working

### ISSUE THREAD

**Issue by DSRoie** [TheComputerizer/Music-Triggers#110]
**Describe the bug**
I chose raining as the trigger and set play once to 2 in hopes that it would play once every time it rained, but it would loop endlessly.

**Comment by DSRoie** [comment]
https://we.tl/t-Zhf7FE2GI6
A video recording the question

**Comment by TheComputerizer** [comment]
Confirmed, this will be fixed in 6.2

**Comment by TheComputerizer** [comment]
This has been fixed in 6.2
