### ISSUE TITLE
[1.19.2] Soft Crash Upon Setting Persistence Value For Victory Trigger

### ISSUE THREAD

**Issue by Korveyus** [TheComputerizer/Music-Triggers#115]
**Minecraft 1.19.2**
**Forge 43.2.8**
**musictriggers-1.19.2-6.2**
**theimpossiblelibrary-1.19.2-0.2.4**

**Describe the bug**
When setting the persistence value for a victory trigger, the game boots me back to the main screen with the following error message: "Internal Exception: java.lang.IllegalStateException: stream has already been operated upon or closed." Upon rejoining my world, the combat trigger associated with said victory trigger no longer works. Nothing shown in the latest.log file except for the error message previously posted.

**To Reproduce**
1.) Create a fresh Minecraft instance. (Minecraft 1.19.2, Forge 43.2.8)
2.) Install mods. (musictriggers-1.19.2-6.2, theimpossiblelibrary-1.19.2-0.2.4
3.) Set up songs/triggers as follows:

[triggers]
	[triggers.universal]
		fade_out = "0"
		persistence = "0"
		trigger_delay = "0"
		song_delay = "0"
		start_delay = "0"
		fade_in = "0"
	[triggers.victory]
		identifier = "zombie_victory"
		priority = "100"
	[triggers.mob]
		identifier = "zombie_combat"
		resource_name = [ "zombie" ]
		level = "1"
		detection_range = "40"
		mob_targeting = false
		victory_id = "zombie_victory"
		priority = "100"
	[triggers.menu]
	[triggers.generic]
[songs]
	[songs.zombie_victory]
		play_once = "1"
		triggers = [ "victory-zombie_victory" ]
	[songs.zombie_combat]
		triggers = [ "mob-zombie_combat" ]
	[songs.menu]
		triggers = [ "menu" ]
	[songs.generic]
		triggers = [ "generic" ]

4.) Change persistence value on victory trigger from 0 to any other number.

**Additional context**
See attached files for additional context. There's a before and after on main/musictriggers.

[latest.log](https://github.com/TheComputerizer/Music-Triggers/files/11362279/latest.log)
[before-main.txt](https://github.com/TheComputerizer/Music-Triggers/files/11362282/before-main.txt)
[after-main.txt](https://github.com/TheComputerizer/Music-Triggers/files/11362283/after-main.txt)
[before-musictriggers.txt](https://github.com/TheComputerizer/Music-Triggers/files/11362280/before-musictriggers.txt)
[after-musictriggers.txt](https://github.com/TheComputerizer/Music-Triggers/files/11362281/after-musictriggers.txt)

**Comment by TheComputerizer** [comment]
Fixed in 6.3
