### ISSUE TITLE
[1.19.2] Attempt at Snow trigger then crash. Clears trigger from file. Then don't work.

### ISSUE THREAD

**Issue by AlphaStyles** [TheComputerizer/Music-Triggers#116]
**Describe the bug**
So when I tried to add a snow trigger it crashed my game. And when I tried to relaunch the game, the game gives off an error resulting in it not being playable and giving only reports. So I went to my "custom_triggers" folder and removed the snowing trigger. I also put in an ogg file instead of MP3 (only this one did I try mp3). My game was working again, but when I tried to create it after using ogg including making sure that it's NOT snowing it doesn't seem to work anymore. Any ideas on how this can be resolved? I don't want to rely on the "rain" trigger since the song I'm using is meant to fit snowing.

**The crash reports**

[crash-2023-05-01_07.35.16-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/11366700/crash-2023-05-01_07.35.16-client.txt)
[crash-2023-05-01_07.35.51-fml.txt](https://github.com/TheComputerizer/Music-Triggers/files/11366701/crash-2023-05-01_07.35.51-fml.txt)
[crash-2023-05-01_07.37.45-fml.txt](https://github.com/TheComputerizer/Music-Triggers/files/11366702/crash-2023-05-01_07.37.45-fml.txt)

**Comment by TheComputerizer** [comment]
`songs.Metroid Prime 3_ Corruption Music- Bryyo (Ice)` Song names cannot have spaces in them as they are unable to be parsed correctly. If you are still having problems after that is resolved, feel free to open a separate issue
