### ISSUE TITLE
[mod: 6.2 ; MC: 1.19.2 ; fabric] Crashes constantly as soon as any songs / triggers are set in main.toml

### ISSUE THREAD

**Issue by MrRobinhq** [TheComputerizer/Music-Triggers#117]
**Describe the bug**
Crashes shortly (~30 sec) after joining world if any songs / triggers are active. Does not crash if no channel has been created.

**To Reproduce**
Steps to reproduce the behavior: Adding any channel with songs & triggers; only used simple triggers (details see attached main.toml); songs are in .mp3 format

**Additional context**
Worked fine the other day in a huge modpack (better MC) but started to crash as I played around with adding songs & triggers. Figured it was most likely some incompatibility with any of the other 200+ mods so I created a fresh instance with only fabric API, Music Triggers and impossible library installed; encountered same issue. I do not know what changed since it used to work for a time (even with multiple songs & triggers set; same version of mod & MC & fabric). Looking at crash reports it always seems to involve "java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1111.method_4770()" because "$$3" is null".

**Attached Files**
[crash-2023-05-02_12.19.42-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/11372239/crash-2023-05-02_12.19.42-client.txt)
[main.toml.txt](https://github.com/TheComputerizer/Music-Triggers/files/11372253/main.toml.txt) just one example config, crash occurs with other triggers

**Comment by MrRobinhq** [comment]
This issue does not occur with 6.1, so downgrading solved my problem

**Comment by TheComputerizer** [comment]
Most likely fixed in 6.3. Feel free to open a separate issue if this is not the case
