### ISSUE TITLE
[6.2 Forge 1.16.5] Songs don't reverse fade

### ISSUE THREAD

**Issue by vitaeum** [TheComputerizer/Music-Triggers#119]
**Describe the bug**
In 5.4, a trigger that was fading out would reliably reverse-fade, or fade the currently playing song back in, if the trigger became active again before it stopped fading. This is no longer the case in 6.2 Forge 1.16.5.

**To Reproduce**
1. Set two different biome triggers and their respective songs
2. Find somewhere in the world where both biomes border each other
3. Once one biome's song starts playing, move into the other biome
4. Before the first biome's song finishes fading out, move back into the first biome
5. The first song will finish fading out instead of fading back in

**Additional context**
This works with any combination of triggers, of course. I am playing on Music Triggers version 6.2 for Forge 1.16.5.

**Comment by vitaeum** [comment]
I just did some further testing. After step 5, the next song that plays in the first trigger will abruptly stop when activating a different trigger, even though it should fade out. This will happen even if the next song in the first trigger is allowed to play for a longer time then its fade out parameter.

**Comment by TheComputerizer** [comment]
Fixed in 6.3
