### ISSUE TITLE
[1.19.2 Forge 43.2.0] Earrape Bug

### ISSUE THREAD

**Issue by Fyshishark** [TheComputerizer/Music-Triggers#122]
**Describe the bug**
Setting the volume of the music somewhere in 0.008566241 in options.txt (or slowly sliding it from 1% to 0%... not OFF) causes the soundtrack to play very loudly.

**To Reproduce**
note: do not use headphone for this bug
1. Go to the settings and set your music volume to 1%
2. Slowly slide it down to 0%
3. Trigger a music.
4. If you did not hear anything, repeat step 2 but very slowly this time.

Alternative way to reproduce the behavior:
1. Open options.txt in .minecraft folder
2. Scroll down till you find "soundCategory_music"
3. Set its value to 0.008566241
4. Trigger a music.

**Additional context**
This may happen if the volume of music is at 0.005 to 0.009, I tried scrolling it from OFF to 0% and it was working normally. But from 1% to 0% causes this earrape bug. I also use .ogg file

Game Version: 1.19.2
Forge Version: 43.2.0
Mod Version: 6.2

**Comment by TheComputerizer** [comment]
It might be something with the volume calculation getting reversed at very low values, which is probably a simple fix of implementing a cap on the low end. I'll take a look

**Comment by TheComputerizer** [comment]
Looks like the volume calculation was reversed but seemingly only when a new trigger or set of triggers was activated. It has been fixed in dev.

**Comment by TheComputerizer** [comment]
Fixed in 6.3
