### ISSUE TITLE
[Feature request] Check the text on boss bar

### ISSUE THREAD

**Issue by Rad586** [TheComputerizer/Music-Triggers#123]
**Describe your idea**
I was wondering if it would be more performant to check the text on boss bar(if player chooses to do so), instead of using a wide detection range for bosses. This should help those who use different themes for different bosses. 
So, if BOSS is included in resource name, there should be something like BOSS_NAME to specify it, with less performance cost. 
**Describe alternatives you've considered**
 
**Additional context**
I don't know much about modding, sorry if it's useless or impossible.

**Comment by TheComputerizer** [comment]
This is something that has already been implemented. Adding additional elements to the resource_name parameter in addition to the BOSS special case acts as a whitelist

**Comment by Rad586** [comment]
![image](https://github.com/TheComputerizer/Music-Triggers/assets/99306685/2062411f-0eec-462e-bd31-355b174aaabd)
So...how do I use the entity ID for bosses? I tried those but none of them works, neither the wiki nor the description in game gives an example. But display name(Wither) works fine when I switch to English(US).

**Comment by TheComputerizer** [comment]
Whatever the display name is should work

**Comment by Rad586** [comment]
> Whatever the display name is should work

Yeah, "Wither" works, but when I try "凋零"(Chinese), it crashes. 
edit: Ascii code doesn't work, too.
