### ISSUE TITLE
[1.18.2 Fabric v6.2] \n in lang file shows incorrectly

### ISSUE THREAD

**Issue by Rad586** [TheComputerizer/Music-Triggers#125]
**Describe the bug**
\n in lang file shows incorrectly. 
![image](https://github.com/TheComputerizer/Music-Triggers/assets/99306685/b3a6d700-8b41-4d52-8453-0969cd66f703)

**To Reproduce**
Use \n in lang file.

**Additional context**
-

**Comment by TheComputerizer** [comment]
It makes sense that /n wouldn't work, but I need more context on which lang key this is specifically you are trying to set

**Comment by Rad586** [comment]
Here's zh_cn.json for 5.2, not making a pull request since it looks buggy.
[zh_cn.json.txt](https://github.com/TheComputerizer/Music-Triggers/files/12098585/zh_cn.json.txt)
![image](https://github.com/TheComputerizer/Music-Triggers/assets/99306685/2c2f0a8e-3cb8-47a9-8c9c-a871ff8d7807)
It is needed for long sentences, some of them goes out of the screen.

**Comment by TheComputerizer** [comment]
Seems like it's an issue with the width of the Chinese characters not getting read properly, since normally strings like that are broken into multiple lines automatically. I'll look into it

**Comment by TheComputerizer** [comment]
The relevant PRs for the lang files have been included in 6.3 so Ill close this unless something else pops up
