### ISSUE TITLE
[Crash][forge 1.18.1] Game crash when i use the recorder.

### ISSUE THREAD

**Issue by Axii98** [TheComputerizer/Music-Triggers#13]
Hi,
After i finished writing my config i launched the game to see if my musics are playing correctly, first i had some crashes due to the victory trigger but it's possibly due to a mistake from me.
I removed the victory music and then i could join a world.
I wanted to know what music was playing when i spawned so i used a recorder, wich had no texture by the way.
I used a blank cd and when it popped out of the recorder the game crashed.

The crash log:
https://pastebin.com/hNh0Rqzi

**Comment by TheComputerizer** [comment]
It looks like the mod always assumes you have menu songs and crashes when you do not. Ill push a fix for this later

**Comment by TheComputerizer** [comment]
This has been fixed in 5.1
