### ISSUE TITLE
[minecraft 1.19.2, forge 43.2.6, mod version 6.2] PLAY_NORMAL_MUSIC config option doesn't work

### ISSUE THREAD

**Issue by vommythegreat** [TheComputerizer/Music-Triggers#131]
**Describe the bug**
The "PLAY_NORMAL_MUSIC" option in debug.toml doesn't work. The vanilla music still doesn't play. Even on the title screen which absolutely should not have any active triggers, the regular music doesn't play.

**To Reproduce**
1. download mod
2. set "PLAY_NORMAL_MUSIC" to true
3. go to the credits or something
4. the music don't play!!!!!

**Additional context**
I'm making a modpack with a lot of mods in it, are there any mods that are incompatible with musictriggers in some way?

**Comment by TheComputerizer** [comment]
I don't remember exactly what the issue was, but this has already been fixed in dev and will be working in 6.3

**Comment by cuboxy** [comment]
I'm also a bit confused about the description of the config option. It says "Allows vanilla and blocked music to play when there is music from Music Triggers already playing" does this mean that vanilla music will play at the same time as music played by Music Triggers? if so, is there a way to make vanilla music play, but only when Music Triggers is not playing music?

**Comment by TheComputerizer** [comment]
Fixed in 6.3
