### ISSUE TITLE
[1.12.2] Problem with Title Color and Subtitle Color in Transition Cards.

### ISSUE THREAD

**Issue by Equinoxtic** [TheComputerizer/Music-Triggers#134]
**Describe the bug**
* Firstly, the colors of Titles and Subtitles seemed to be mixed up. (e.g.: Subtitle color is red colors the title instead and vice-versa.)
* Secondly, some colors don't display the correct colors. (e.g.: Putting purple as title color outputs to a wrong color such as orange)

**To Reproduce**
* Create a Title Card.
* Set a message / string to be on the Title and Subtitles.
* Set the Title and Subtitle's colors.

**Additional context**
* No further context rather than playing on version 1.12.2 on the latest release of Music Triggers in said version

**Comment by TheComputerizer** [comment]
I will look into this

**Comment by TheComputerizer** [comment]
Probably fixed in 6.3, feel free to open a separate issue if this is not the case
