### ISSUE TITLE
[1.12.2] Crash when opening in-game config GUI

### ISSUE THREAD

**Issue by michelegargiulo** [TheComputerizer/Music-Triggers#139]
**Describe the bug**
The game crashes as soon as it tries to render the in game music triggers GUI

**To Reproduce**
Enter in world, press the key to open the GUI

**Additional context**
Crash log attached: 
[crash-2023-09-01_16.38.42-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/12515297/crash-2023-09-01_16.38.42-client.txt)

**Comment by TheComputerizer** [comment]
You were using an incompatible version of The Impossible Library, but 6.3 has been released which updates the compatibility to the latest version
