### ISSUE TITLE
[Bugs][Crash][Forge 1.16.] Music won't switch + Strange Volume Alterations, Crash when tabbing out

### ISSUE THREAD

**Issue by Huetete** [TheComputerizer/Music-Triggers#14]
These problems started after the rework of the fade parameters and, probably, the new Universal Block Feature included. 

1) The Music won't switch sometimes. It seems that this occurs when I am switching fast from biome to biome and daytime. In a beginning, the songs switch normally, but sooner or later these start to fail and get "stuck" (the music won't switch) and happens some volume alterations when, for example, switching from a biome to another (The volume lowers or levels up whenever I cross the invisible "border" between two biomes).

2) Volume it's altered if I tweak the vanilla music faders. Even if I let the fade back to how it was, the volume isn't the same (you hear it lower than it actually is).

3) Game crashes tabbing out, especially if you're inside the mod's In-Game GUI

• Game Log: https://paste.ee/p/3ohMa
• Crash Report: https://rentry.co/fmpou

----------

I'll try to do the effort to upload my whole config folder if it's necessary, although it is more than 1,6 GB. I hope that's not a problem. Yeah, I know I am persistent, but I have never had such love for a mod like this before!

**Comment by TheComputerizer** [comment]
These should have all been fixed in 5.1
