### ISSUE TITLE
[1.16.5 Forge v6.3] The game always crashes when opened

### ISSUE THREAD

**Issue by qing0235** [TheComputerizer/Music-Triggers#141]
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading Twitch main page failed.

The game always crashes when opened.

**Comment by qing0235** [comment]
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading Twitch main page failed.

**Comment by TheComputerizer** [comment]
Did you not have an internet connection while running the game or do you just not have access to twitch where you live?

**Comment by qing0235** [comment]
Both of them. How should we play minecraft with this mod offline? In many times, our internet is not always very good. I would appreciate it if you could add it to the config.

**Comment by TheComputerizer** [comment]
I'll add a catch for the online sources

**Comment by qing0235** [comment]
Thank you for your efforts.
Hope to see the fix on curseforge or github soon!

**Comment by qing0235** [comment]
I found that a folder called code is downloaded in the parent directory of ./minecraft, which I think should be the behavior of this mod. Can you move it to the appropriate place, such as ./minecraft?

**Comment by TheComputerizer** [comment]
That's not something from Music Triggers. For future reference it is usually better to open separate issues when you run into a seemingly unrelated problem. 

Also since the crash has more info in #142 I'll close this one.
