### ISSUE TITLE
[1.12] Crash when using debug menu

### ISSUE THREAD

**Issue by CalaMariGold** [TheComputerizer/Music-Triggers#143]
Enable debug menu, then every now and then when I click reload config after making changes in the cfg file, the game crashes

https://mclo.gs/Seqq9CG

**Comment by CalaMariGold** [comment]
This also occurs on player death

**Comment by TheComputerizer** [comment]
Seems like the debug info didn't like one of your GUI classes. I'll add a catch for that

**Comment by TheComputerizer** [comment]
Fixed in 6.3.1

**Comment by TheComputerizer** [comment]
Ok so the issue isn't actually fixed since for some reason I decided to log the error with the same method that crashes it, but the root of the issue is The Impossible library so I've moved the issue over there TheComputerizer/The-Impossible-Library#15
