### ISSUE TITLE
[1.12.2 - 6.3] issue title

### ISSUE THREAD

**Issue by milkev** [TheComputerizer/Music-Triggers#146]
**Describe the bug**
The game crashes almost immediately after launching.

**To Reproduce**
Install Music triggers & its dependents (The Impossible library & MixinBooter)

**Additional context**
Im using;
Forge 1.12.2 - 14.23.5.2860
Music Triggers 1.12.2 - 6.3
The impossible Library 1.12.2-0.2.3
Mixin Booter 1.12.2 - 8.6 (i also tried using version 8.4, which made no difference)
[latest.log](https://github.com/TheComputerizer/Music-Triggers/files/13198601/latest.log)

**Comment by TheComputerizer** [comment]
Update The Impossible Library to 0.3.0 and it will work. MT 6.3 is incompatible with versions before that

**Comment by milkev** [comment]
No clue how i didnt see that, I thought i had downloaded the latest version for 1.12.2. my bad!
