### ISSUE TITLE
not showing identifier option for me for some reason but the mod is on fabric 1.19.2

### ISSUE THREAD

**Issue by zeppelinlz99** [TheComputerizer/Music-Triggers#148]
<img width="1920" alt="2023-11-05" src="https://github.com/TheComputerizer/Music-Triggers/assets/149930006/96793c20-5332-4b50-b7ae-49502eb339a3">
**Describe the bug**
not showing identifier option for me for some reason
**To Reproduce**

**Additional context**
Add any other context about the problem here. Remember to add the version of the game and mod you are using

**Comment by TheComputerizer** [comment]
Those are the universal trigger parameters. Identifiers are only relevant to trigger holders
