### ISSUE TITLE
[1.16.5] Incorrect music volume after fade

### ISSUE THREAD

**Issue by zaeonNineZero** [TheComputerizer/Music-Triggers#15]
Probably the same issue as the second issue mentioned in #14 

After a music track finishes fading in, the playback sound volume jumps to 100% until the track fades out or the music volume slider is manually changed.  In the case of a track fading out, the new track will fade in taking the volume setting into account before jumping back to 100% volume.

Note that the volume setting in the options menu isn't bumped to 100% - the music track seems to ignore the music volume slider altogether when it's not fading in or out.

**Comment by TheComputerizer** [comment]
This has been fixed in 5.1
