### ISSUE TITLE
1.18.2 - Game fails to launch due to mixin

### ISSUE THREAD

**Issue by Spenz0r** [TheComputerizer/Music-Triggers#156]
**Describe the bug**
The game crashes on startup due to a font mixin conflicting with some other mods, for example, oc2.

![image](https://github.com/TheComputerizer/Music-Triggers/assets/118317984/fdc20ac7-02f5-4b94-a703-25b87fcfec7a)

**Comment by TheComputerizer** [comment]
Please open this issue in the [correct repository](https://github.com/TheComputerizer/The-Impossible-Library/issues)
