### ISSUE TITLE
[1.16.5] Game crash on exiting a world

### ISSUE THREAD

**Issue by zaeonNineZero** [TheComputerizer/Music-Triggers#16]
On exiting a world, the game crashes before reaching the main menu with an 'unexpected error.'

"Description: Unexpected error
 
java.lang.NullPointerException: Unexpected error
	at mods.thecomputerizer.musictriggers.client.MusicPlayer.onTick(MusicPlayer.java:107) ~[?:5.0] {re:classloading,re:mixin}"

Full crash report here:
https://pastebin.com/N47M6kJ2

**Comment by TheComputerizer** [comment]
This has been fixed in 5.1
