### ISSUE TITLE
CTD when play_once=2

### ISSUE THREAD

**Issue by TensoUchiha** [TheComputerizer/Music-Triggers#19]
[crash-2022-04-16_02.46.20-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/8498995/crash-2022-04-16_02.46.20-client.txt)
Always crashes when song finishes playing.
Easily replicated and confirmed on multiple machines.
Running MusicTriggers and MixinBootstrap as the only mods.
Clean install otherwise.

**Comment by TheComputerizer** [comment]
I probably should have responded to this, it will be fixed this weekend sometime

**Comment by TheComputerizer** [comment]
This has been fixed in 5.2
