### ISSUE TITLE
[Enhancement] Allowing the usage of links to various platforms for music as well as files?

### ISSUE THREAD

**Issue by Corvus20** [TheComputerizer/Music-Triggers#2]
Hycraft's [Music Player](https://www.curseforge.com/minecraft/mc-mods/music-player) mod pulled this off, and I have always wanted a mod that would bridge the gap between the trigger based music mods and Music Player. Not sure how feasible or practical this would be to implement, but I think it should at least be considered. Allowing for people to put links to soundcloud, youtube, etc. to add music would make life a lot easier for a lot of people.

**Comment by TheComputerizer** [comment]
I haven't forgotten about this and would still like to get it implemented. I will attempting to implement it after the current round of issues for 5.0 have all been fixed
