### ISSUE TITLE
[Crash Report] 1.12.2 random crashing involving going back to the menu

### ISSUE THREAD

**Issue by roccscout** [TheComputerizer/Music-Triggers#21]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (!mixinbooter-4.2.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  Music Triggers Core (musictriggers-1.12.2-5.1-hf.jar)
  midnight (themidnight-0.3.5.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 4/22/22 10:50 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mods.thecomputerizer.musictriggers.client.MusicPlayer.onTick(MusicPlayer.java:299)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_17_MusicPlayer_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_312, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 1499828440 bytes (1430 MB) / 1833435136 bytes (1748 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version      | Source                                        | Signature                                |
	|:------ |:------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft     | 1.12.2       | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp           | 9.42         | minecraft.jar                                 | None                                     |
	| LCHIJA | mixinbooter   | 4.2          | minecraft.jar                                 | None                                     |
	| LCHIJA | FML           | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge         | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | biomesoplenty | 7.0.1.2444   | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| LCHIJA | llibrary      | 1.7.19       | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs   | 1.5.8        | mowziesmobs-1.5.8.jar                         | None                                     |
	| LCHIJA | musictriggers | 1.12.2-5.1   | musictriggers-1.12.2-5.1-hf.jar               | None                                     |
	| LCHIJA | nyx           | 1.5.1        | Nyx-1.5.1.jar                                 | None                                     |
	| LCHIJA | beneath       | 1.7.0        | The Beneath-1.12.2-1.7.0.jar                  | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | midnight      | 0.3.5        | themidnight-0.3.5.jar                         | None                                     |

	Loaded coremods (and transformers): 
MixinBooter (!mixinbooter-4.2.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Music Triggers Core (musictriggers-1.12.2-5.1-hf.jar)
  
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.79' Renderer: 'NVIDIA GeForce RTX 3080/PCIe/SSE2'
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.79, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 9
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 511.79
	OpenGlRenderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by TheComputerizer** [comment]
This should be fixed in 5.2
