### ISSUE TITLE
[1.16.5-5.2-hf] GUI Issues + Music Linking not working properly

### ISSUE THREAD

**Issue by Huetete** [TheComputerizer/Music-Triggers#23]
In regard to the GUI:

1) "Refresh Debug" doesn't work properly and it doesn't save the changes applied in it.
2) "Applying All Changes" freezes the game near the end of the resource pack reloading
3) Spontaneous crash when opening the GUI:

- Crash Report
https://pastebin.com/NwewpcM6

- Log Report (Last lines)
https://pastebin.com/9cxmbPrT

In Regard to the Music Linking:

Probably since the Trigger Blocker doesn't work or doesn't let the instantiated trigger to be used later for music linking, in general, the music linking can't work properly probably because the instantiated trigger overrides the linking itself. I tried many ways to use music linking: trying a blocker with a non-existent trigger with `name = "blocker"` and  `is_instantiated = "true"`, not using any blocker, lowering the instantiated trigger's priority below to the base song. None of these worked and any of the songs do not play at the same time, thus can't exist a smooth transition between them.

**Comment by TheComputerizer** [comment]
The issues with the gui and trigger blockers were fixed, which should fix most of the other related issues for 5.3. 

Open a separate issues with the problems that still occur if you need to
