### ISSUE TITLE
[1.16.5-5.2-hf] Another reverse-fade trigger issue.

### ISSUE THREAD

**Issue by zaeonNineZero** [TheComputerizer/Music-Triggers#24]
**Issue:**
Similar to #18 in nature, though not as severe in this case.  If a song is reverse-fading, it will temporarily ignore trigger changes and continue to play, even if its trigger is deactivated during the reverse-fade process.  The issue quickly fixes itself when another trigger change occurs, which will cause the song to fade out if its trigger wasn't reactivated.

Tested with instances of the biome and height triggers, and probably applies to all triggers.  This is easiest tested if you set the fade-out time to a value above 40-60 ticks, that way you have time to re-activate a song's trigger and change biomes or height while the song is reverse-fading.  Presumably does not happen when the fade-out time is set to 0.

**Comment by Huetete** [comment]
I can confirm.

**Comment by TheComputerizer** [comment]
Fixed in 5.3
