### ISSUE TITLE
[1.16.5-5.2-hf] Crash on activating the 'storming' trigger.

### ISSUE THREAD

**Issue by zaeonNineZero** [TheComputerizer/Music-Triggers#26]
Upon activating the 'storming' music trigger, the game client crashes with a 'java.lang.NullPointerException: Unexpected error' exception. (See crash report for details)  This also prevents the world from loading so long as the 'storming' trigger is active.

Removing the 'storming' trigger from any song block(s) that use it prevents the crash from occuring.

**Relevant config information**
Here is the portion of my musictriggers.toml file that uses the 'storming' trigger:

_[stormy]
    [[stormy.trigger]]
        name = "storming"
        priority = "16"
        id = "stormy"
    [[stormy.trigger]]
        name = "dimension"
        id = "overworld"_

**Crash Report:**
[crash-2022-04-26_17.06.35-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/8566899/crash-2022-04-26_17.06.35-client.txt)

This may be a config-related issue, so please let me know if I need to make a change in my config section.  Also please let me know if I should provide additional info/data to help with resolving this issue.

**Comment by TheComputerizer** [comment]
The storming trigger does not have an identifier

**Comment by zaeonNineZero** [comment]
I completely overlooked that in the wiki.  Thanks!
