### ISSUE TITLE
[1.16.5-5.2-hf] Reverse Fade: Stuck Music Returns

### ISSUE THREAD

**Issue by Huetete** [TheComputerizer/Music-Triggers#27]
I really apologize for the video's quality, my internet is trash and I have to make it the less heavy possible, but I think the music and what's happening here is still comprehensible enough. So, reverse fade is still causing problems with the music getting stuck; not changing when its respective trigger is not playing anymore.

https://drive.google.com/file/d/1kfRU9Rlwx4XXNYQJcbciY-i8GAKgwl4I/view?usp=sharing

**Comment by zaeonNineZero** [comment]
Same issue in #24 with songs ignoring triggers when reverse fading, so can confirm on my end as well.

**Comment by TheComputerizer** [comment]
Defeated in 5.3
