### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by SeanChengN** [TheComputerizer/Music-Triggers#3]
Can't start the game normally
[crash-2021-11-04_17.50.31-fml.txt](https://github.com/TheComputerizer/Music-Triggers/files/7473854/crash-2021-11-04_17.50.31-fml.txt)

**Comment by TheComputerizer** [comment]
Which version of the mod are you running?

**Comment by SeanChengN** [comment]
Its musictriggers-1.16.5-3.2's log:
[crash-2021-11-04_20.55.06-fml.txt](https://github.com/TheComputerizer/Music-Triggers/files/7474873/crash-2021-11-04_20.55.06-fml.txt)

**Comment by TheComputerizer** [comment]
Looks like I forgot to add a check for an empty config. It should work fine once you add some songs in and that will be fixed next update

**Comment by TheComputerizer** [comment]
This has been fixed as of version 3.3
