### ISSUE TITLE
[1.16.5-5.3] In-Game GUI's Debug Issue

### ISSUE THREAD

**Issue by Huetete** [TheComputerizer/Music-Triggers#35]
`ShowDebugInfo` won't change even if I set it to `true` through the In-Game GUI. When I refresh using the `Refresh Debug` button, it won't do anything. If you get back to the GUI's main menu and then return back again, you will see the changes aren't saved. In addition to it, trying to click the `Reload` or `Apply All Changes` buttons will crash the game since, in the debug config, it will remove the quote marks inside the brackets right after the blocked mod list.

**Comment by TheComputerizer** [comment]
I cant reproduce the Refresh Debug issue
