### ISSUE TITLE
[Enhancement] mod_list paramater for Mob Trigger

### ISSUE THREAD

**Issue by Huetete** [TheComputerizer/Music-Triggers#37]
`mod_list = "modid"` parameter for **Mob Trigger**, analogous to `biome_category` for **Biome Trigger**. You can generalize a song for only an array of mobs belonging to a mod, that can be combined with MOB and BOSS labels in resource_name, limiting these only to the mobs that come from that specific mod. It could use lists.

An example: `mod_list = "alexsmobs;infernalexp;..."`

**Comment by TheComputerizer** [comment]
mob ids can be regexed in 5.4 now
