### ISSUE TITLE
Image transitions aren't centered

### ISSUE THREAD

**Issue by Jetpack-Cat** [TheComputerizer/Music-Triggers#38]
1.16.5 Forge Music triggers 5.3
```
[[image]]
	triggers = [ "time-night" ]
	name = "warningnightfall"
	time = "180"
	horizontal = "-640"
	fade_in = "130"
	fade_out = "60"
```

This will center the image for me when playing at 1080p, but doesn't work if the game resolution changes to 2560x1440. The different between playing fullscreen with it set to 1080p and just maximizing the game.

**Comment by TheComputerizer** [comment]
fixed in 5.4
