### ISSUE TITLE
[Entity name] Is it more compatible to use entity id?

### ISSUE THREAD

**Issue by SeanChengN** [TheComputerizer/Music-Triggers#4]
Today I discovered the reason why the music has not worked since multiple versions, because of the entity name.

For example:
![notepad++_L9MxZXpbwR](https://user-images.githubusercontent.com/20624068/140845844-2c0c3a34-cfca-40ed-9308-a79359d12cd4.png)
![2021-11-09_09 27 33](https://user-images.githubusercontent.com/20624068/140845902-fffda4d4-e4d4-4903-8df3-cb981224a293.png)
The entity name is the same as in the config, so the music plays normally.

**However, if I switch to another language, the entity name will change and the music cannot be played.**

For example:
![2021-11-09_09 28 13](https://user-images.githubusercontent.com/20624068/140846194-e960c38d-9ef4-4d8b-ba87-8d0f26dafe44.png)

**In addition, I also tried to modify the name in the config to other languages, but it will cause garbled characters when the game is restarted.**
![notepad++_8TpjyE6h1N](https://user-images.githubusercontent.com/20624068/140846656-597365d3-acf2-4d21-971f-f8d402bd78e0.png)

**Is it more compatible to use entity id in config? like minecraft:wither or a better way you know.**

**Comment by TheComputerizer** [comment]
I was actually planning on expanding the mob trigger next update to allow for the use of either mob names or mob resource locations. This is definitely good to know

**Comment by SeanChengN** [comment]
> I was actually planning on expanding the mob trigger next update to allow for the use of either mob names or mob resource locations. This is definitely good to know

Amazing, waiting for your good news.

**Comment by TheComputerizer** [comment]
Added support for mob resource locations in V4.0
