### ISSUE TITLE
Mob trigger not working

### ISSUE THREAD

**Issue by bmil2661** [TheComputerizer/Music-Triggers#43]
Mob trigger isn't working on anything, the only time it seems to work is on the first ender dragon fight, but will not work when it respawns. I have also done tests on other vanilla mobs, with no luck

[enderdragon]
	[enderdragon.trigger]
		name = "mob"
		priority = "15"
		fade_in = "60"
		resource_name = "minecraft:ender_dragon"
		detection_range = "640"
		fade_out = "640"

[voidworm]
	[voidworm.trigger]
		name = "mob"
		priority = "15"
		fade_in = "60"
		resource_name = "alexsmobs:void_worm"
		detection_range = "640"
		fade_out = "60"

[mosco]
	[mosco.trigger]
		name = "mob"
		priority = "15"
		fade_in = "60"
		resource_name = "alexsmobs:warped_mosco"
		detection_range = "640"
		fade_out = "60"

[wither]
	[wither.trigger]
		name = "mob"
		priority = "15"
		fade_in = "60"
		resource_name = "minecraft:wither"
		detection_range = "640"
		fade_out = "60"

**Comment by TheComputerizer** [comment]
You need different [identifiers](https://github.com/TheComputerizer/Music-Triggers/wiki/Identifier-System) for different mobs, otherwise you are just adding songs to the same trigger
