### ISSUE TITLE
Request: make transitions callable by a command

### ISSUE THREAD

**Issue by Jetpack-Cat** [TheComputerizer/Music-Triggers#45]
Forge 1.16.5
This would allow us to use other mods that can execute commands when specific things happen to call up a transition image instead of needing a music trigger to do it. Sometimes I want to show an image on the screen, but not with a music trigger. 

- When I get a specific item in my inventory I could show an image on the screen that explains something about that item or shows an animation for user experience.
- I have a setup where when you go to the nether, if you "observe" a specific mob, essentially if you look at the mob from within 5 blocks it uses a command to show a message giving the location of a nether fortress, but it only works once every time you visit the nether, so as to not spam the fortress coords every time they're near this mob, they also have to look at the mob within that distance, not just be within 5 blocks of that mob when it's passing by. I don't want music to play during any of this, I just want an animation to show on the screen.
- I play SFX on top of music when certain things happen, I don't want to do anything with music when these things happen, I don't want to interrupt it or change it, I just want to show an animation or image on screen when I have certain things happen.

There's a ton of use cases that music triggers isn't capable of doing.

**Comment by TheComputerizer** [comment]
Putting this off to 6.0

**Comment by TheComputerizer** [comment]
You can do this via the command trigger introduced in 6.0 now
