### ISSUE TITLE
[1.18.2-5.4-hf] F1 not working

### ISSUE THREAD

**Issue by DejaVu42069** [TheComputerizer/Music-Triggers#52]
**Describe the bug**
When trying to hide ui, the ui will just flicker and not hide

**To Reproduce**
1. Install Music Triggers and Fabric API.
2. Enter a world
3. Try to hide ui.
https://user-images.githubusercontent.com/76191961/170153464-21cbde0f-b291-4809-9186-8c3d56db2bf1.mp4

**Additional context**
Minecraft 1.18.2 Fabric, Music Trigger 5.4-hf
Fabric API and Music Trigger are the only mods installed.

**Comment by muhammedesadcomert** [comment]
I can confirm this issue exists.
I've been looking for the mod causing this for days, thanks for opening the issue.

**Comment by TofuToons** [comment]
I can also confirm this is an issue and exists not only in 5.4-hf but every version available for 1.18.2 fabric

**Comment by TheComputerizer** [comment]
This has been fixed in 6.0
