### ISSUE TITLE
[Feature request] Allow Referencing Vanilla Sounds

### ISSUE THREAD

**Issue by Darkosto** [TheComputerizer/Music-Triggers#59]
Hello!

**Describe your idea**
I've been wanting to use this mod due to how comprehensive its features are. I do have one question / request for you: Is there a way to reference vanilla minecraft sounds without having to download the .ogg files and copy them into the music triggers folder? I have a few vanilla sounds I'd like to use and a reference would be an easy way to get that done.

**Describe alternatives you've considered**
I can locate the .ogg files from the game and use those instead. I don't think this is the most ideal way.

Thank you for your time!
Darkosto

**Comment by TheComputerizer** [comment]
You are in luck, I was actually already planning on being able to redirect to any registered sound in 6.0

**Comment by TheComputerizer** [comment]
This has been added in 6.0 via the redirect file
