### ISSUE TITLE
Checking NBT

### ISSUE THREAD

**Issue by DRACTION** [TheComputerizer/Music-Triggers#6]
Hi I'm new to GitHub, don't speak English well and NULL in Java.

------------------------------------------------------------
1.16.5-3.5

There is a bug when this mod works with the **EnderMail** and **SnailMail** mods.
I looked at the logs, your mod does **"ent.serializeNBT()"** and this causes the **"Saving entity NBT"** to crash when creating a mob from these mods.
I tried commenting out the loop with actions on "pet", thereby breaking the possibilities with pets, but that removed the crashes.
I am 40% sure that this check can break other interactions from mods.

Line with checking

- https://github.com/TheComputerizer/Music-Triggers/blob/9ca998cd4df68f36b8b4611c5df90c553647d0f6/src/main/java/mods/thecomputerizer/musictriggers/client/MusicPicker.java#L317

Logs:
[2021-12-12-6.log](https://github.com/TheComputerizer/Music-Triggers/files/7698363/2021-12-12-6.log)

**Comment by TheComputerizer** [comment]
Right, I forgot to respond to this, but it should be fixed with the update tomorrow. Thanks for reporting

**Comment by TheComputerizer** [comment]
Fixed in V4.0
