### ISSUE TITLE
Crash when attempting to open GUI

### ISSUE THREAD

**Issue by a-random-something** [TheComputerizer/Music-Triggers#60]
When Pressing r on the keyboard in version 5.4 of the mod to open the GUI, the game crashed. Was in a modpack with several other mods, but none overwrite the keybind. Also, changes to musictriggers.json were recently made, but the crash still happened even after undoing them.
 Crash report: https://pastebin.com/JGLxmq7m

**Comment by TheComputerizer** [comment]
Which MC version are you running?

**Comment by a-random-something** [comment]
Forge 1.16.5

**Comment by a-random-something** [comment]
For some reason, it seems to work now. Accidentally hit the key and it brought up the menu and didn't crash the game. I didn't change anything at all as far as I know. Weird.

**Comment by TheComputerizer** [comment]
I will leave this open until 6.0 comes out just in case someone else has the same issue and can provide more information

**Comment by a-random-something** [comment]
I think I figured it out. It only seems to happen with MultiMC. On curseforge or any other launcher that I've tested, it seems to work fine.

**Comment by TheComputerizer** [comment]
The gui was overhauled so this should not be an issue anymore. Feel free to open a separate issue if you continue to have problems
