### ISSUE TITLE
Allow Audio to be Routed to Another Audio Channel (Such as Ambient/environment)

### ISSUE THREAD

**Issue by Darkosto** [TheComputerizer/Music-Triggers#61]
Hey!

**Describe your idea**
I've been having a good time configuring this mod and it has a lot of potential for my project. Is there any possibility you would consider allowing audio tracks to instead be routed to another specified channel such as "Ambeint/Environment". I was hoping I could setup specific audio and route it to the proper location. I know this is outside of the score of "Music Triggers" but given the functionality of your configs it could be a powerful tool. I believe Music Triggers can only play 1 audio track at a time so that might be a lot more to ask of you.

**Describe alternatives you've considered**
The only other option would be to download another mod and set it up that way. Basically, have Music Triggers running background audio while another mod played shorter ambient sounds on top.

**Additional context**
My goal is setup a modpack that has an overworld that is 750 blocks tall and each layer of about ~150 blocks has a different set of sounds and ambience. Currently, I can do a portion of this with music triggers but that still leaves me with the shorter audio fx sounds.

Thank you!

**Comment by TheComputerizer** [comment]
You are 2 for 2 on requesting upcoming features. I guess you will probably like the 6.0 update once that comes out. 

The channel system has actually already been implemented in the latest beta where you can assign a group of configs to a specific registered audio channel (music, master, ambient, voice, etc).

If you are interested in trying the 6.0 betas btw, you can do it through the discord server. Just check the announcements channel for more information there.

**Comment by Darkosto** [comment]
Sounds awesome! Thanks for all your hard work!

**Comment by TheComputerizer** [comment]
This has been added in 6.0 via the redirect file
