### ISSUE TITLE
[1.12.2 Forge, Mod Version: 5.4hf] Crash due to both "height" and "lowhp" triggers.

### ISSUE THREAD

**Issue by ChrisLensFlare** [TheComputerizer/Music-Triggers#62]
Game crashes on startup, caused by both "height" and "lowhp" triggers, as game did not crash when those parameters were removed.
This is most likely my own problem, caused by my own incompetence, however I can't for the life of me figure out what was done wrong.

Config file: https://pastebin.com/YP99z6Zd
Crash report: https://pastebin.com/STCQQzpi

**1.12.2, musictriggers-1.12.2-5.4-hf**

**Comment by ChrisLensFlare** [comment]
Also having this issue with the "mob" trigger:

`[zombiechoir_01]
    [zombiechoir_01.trigger]
	name = "mob"
	delay = "6700"
	priority = "2"
	level = "6"
	resource_name = "minecraft:zombie"
	victory = "false"
	identifier = "zombiechoir"
`

**Comment by TheComputerizer** [comment]
Regarding quite a few of the songs in your config file, song names cannot have capital letters in them. The song files should have gotten converted automatically, but your config file should also reflect that

**Comment by ChrisLensFlare** [comment]
Thank you, however after replacing all capital letters with lower case, it still does not work. Virtually same crash file. 
I have no doubt the capital letters were causing issues, but I still am stumped. Would it have to do with the order of the trigger information?

**Comment by TheComputerizer** [comment]
Songs can now have capital letters in them and various other things have been fixed in 6.0
