### ISSUE TITLE
[1.18.2 forge] Crash caused by Incompatibility with Oculus

### ISSUE THREAD

**Issue by RedBeast1959** [TheComputerizer/Music-Triggers#63]
![3](https://user-images.githubusercontent.com/100399264/183300606-6ca3be43-ca87-4ce7-a8a7-dfa60656a828.PNG)

Game crashed on night time music trigger of specific music for modded biome.
First night time trigger for vanilla biome and daytime trigger for same modded biome works though

![1](https://user-images.githubusercontent.com/100399264/183300685-143d50ac-1c79-4798-9d52-79361e5a230e.PNG)

When I saw crash report generated by Not Enough Crash mod, suspected mod was Oculus.
So I temporaly disabled it, then night time music trigger works fine without crash.
Too bad I can't use this mod with shader, because I really don't want to use Optifine which cause lots of troubles with other mods.

+@
Welp, I tested it with Optifine and it crash just like Oculus :(

*crash report
[crash.txt](https://github.com/TheComputerizer/Music-Triggers/files/9277136/crash.txt)

*musictriggers.toml excerpt
[musictrigger.txt](https://github.com/TheComputerizer/Music-Triggers/files/9277118/musictrigger.txt)

*1.18.2 forge 40.1.68
musictriggers-1.18.2-5.4-hf.jar
oculus-mc1.18.2-1.2.5.jar
rubidium-0.5.3.jar
BiomesOPlenty-1.18.2-16.0.0.134.jar
TerraBlender-forge-1.18.2-1.1.0.99.jar

**Comment by TheComputerizer** [comment]
Noted I will look into this for 6.0

**Comment by TheComputerizer** [comment]
Did you make sure that it did not crash without this mod when in that biome at night time when oculus was installed?

**Comment by TheComputerizer** [comment]
This has probably been fixed, feel free to open a separate issue if you are still having issues
