### ISSUE TITLE
[1.18.2 Forge] Game crashes when using record on music recorded

### ISSUE THREAD

**Issue by mijospe** [TheComputerizer/Music-Triggers#64]
When you right click on the music recorder with an empty record, when you hear the bang, the game freezes and it crashes right after. The same happens if you try and add a loop.

I tried it with forge 1.18.2 5.4 hf and forge 1.18.2  5.4 without any other mods active in singleplayer.

**Comment by TheComputerizer** [comment]
What kind of bang and do you have a log and config to go along with that?

**Comment by mijospe** [comment]
There is like this anvil sound normally when you right click on it and it normally makes the music disc, but instead it plays the sound for half a second like a loud bang and then crashes the game

[crash-2022-08-12_12.54.05-server.txt](https://github.com/TheComputerizer/Music-Triggers/files/9315743/crash-2022-08-12_12.54.05-server.txt)

[latest.log](https://github.com/TheComputerizer/Music-Triggers/files/9315756/latest.log)

idk about the config file. This is the first time reporting a bug, so I don't know where to find that

**Comment by TheComputerizer** [comment]
If you do not have any songs set and try to record something, it would have that kind of crash

**Comment by mijospe** [comment]
How do you set songs? Cause I have music in the music folder

**Comment by TheComputerizer** [comment]
I would recommend taking a look at the [file structure](https://github.com/TheComputerizer/Music-Triggers/wiki/File-Structure) and [basics](https://github.com/TheComputerizer/Music-Triggers/wiki/The-Basics) part of the wiki

**Comment by TheComputerizer** [comment]
You can now set custom music discs separate from trigger based songs in 6.0, so I will be closing this
