### ISSUE TITLE
[5.4] Null pointer exception

### ISSUE THREAD

**Issue by Madmonkeman** [TheComputerizer/Music-Triggers#65]
[crash-2022-08-16_23.59.11-fml.txt](https://github.com/TheComputerizer/Music-Triggers/files/9356798/crash-2022-08-16_23.59.11-fml.txt)

**Comment by Madmonkeman** [comment]
[musictriggers.txt](https://github.com/TheComputerizer/Music-Triggers/files/9356848/musictriggers.txt)

I made a copy of the config file as a txt. The TOML file is still in the folder.

**Comment by Madmonkeman** [comment]
I did some testing and I think the issue is that it's not recognizing Enhanced Celestials

**Comment by TheComputerizer** [comment]
Oh yeah I forgot to respond to this, but the bluemoon trigger is bugged in 5.4 since I forgot to add it to the list of triggers

**Comment by Madmonkeman** [comment]
Ok thanks
