### ISSUE TITLE
[5.4] Plays random music at the same time as the correct songs.

### ISSUE THREAD

**Issue by Madmonkeman** [TheComputerizer/Music-Triggers#66]
**Describe the bug**
The correct songs will play, however, it will also play one of the songs in the songs folder in addition to it but much louder. For example, the "day" music will play when it's daytime but then all of a sudden the "rain" music will start playing on top of that despite it not raining. It will then play it at a much higher volume and when I set the volume to 0 the "rain" music will keep playing while the correct music will be at 0 volume.

Here is my config
[musictriggers.txt](https://github.com/TheComputerizer/Music-Triggers/files/9387982/musictriggers.txt)

**Additional context**
I am using 1.16.5 and these are the other mods I am using:

Alex's Mobs
Antique Atlas
Architectury API
Ars Arsenal
Ars Creo
Ars Elemental
Ars Nouveau
Atum 2
Better FPS
Better End
Better Nether
Blueprint
Bookshelf
Bountiful
Chococraft
Citadel
Cloth Config API
Coins JE
Cosmetic Armor Reworked
Create
Creatures and Beasts
Curios API
Danny's Expansion
Dungeons Content
Dynamic Surroundings
Enhanced Celestials
Exotic Critters
Fairy Lights
Flywheel
Future Pack
GeckoLib
Gemspark
Gemspork
Geode
Goblin Traders
Goblins and Dungeons
Goblins Community
Gravestone
Help Wanted
HT's Treechop
HWYLA
Ice and Fire
Illagers+
JEI
Kobolds
Kotlin
Litewolf Core
Locks
Magitek Mechs
Magma Monsters
Masks Hats Mod
MC Story Mode Armors
MCA Reborn
Medieval Craft
Moonlight Lib
Mr Crayfish's Furniture
Mutant Beasts
Mutants More
Nether's Delight
NoCube's Sea Dwellers
Off Hand Combat
Patchouli
Replay Mod
Repurposed Structures
Restored Earth
Serene Seasons
Simple World Timer
Sky Villages
Sophisticated Backpacks
Stoneholm
Structure Gel API
Supplementaries
Survivable Deserts
Tax' Deep Villager
Tax' Ocean Villager
Terraforged
The Abyss II
The Farlanders
The Lost Cities
The Undergarden
Towers of the Wild
Towers of the Wild: Additions
Valhesia Core
Valhesia Structures
Waystones
Whisperwoods
Wyrmroost
Yung's API
Yung's Better Caves
Yung's Better Dungeons
Yung's Better Mineshafts
Yung's Better Strongholds

**Comment by TheComputerizer** [comment]
That would be sophisticated backpacks actually. I think that mod either takes from all registered music or all music registered to discs, so it won't be a problem once 6.0 gets released

**Comment by Madmonkeman** [comment]
Thanks I had no idea that Sophisticated Backpacks did that

**Comment by TheComputerizer** [comment]
This is no longer an issue in 6.0
