### ISSUE TITLE
Game crashes after applying changes

### ISSUE THREAD

**Issue by Nolascoeli0** [TheComputerizer/Music-Triggers#67]
Im working on a medieval map and I’m using custom npcs. However, I wanted to hsve custom music for boss battles and different scenarios, so I downloaded this mod. The thing is i don’t even know how it works. The stuff in the wiki with all of the brackets is confusing cuz i don’t see that in the gui. But also, another issue is that when I try to edit a song and apply a trigger, it either doesn’t play and only has a ticking sound on constant loop, or the game crashes. So I’m asking how to use the mod and why it crashes and if there’s any incompatibility with any mods?

**Comment by TheComputerizer** [comment]
The gui is getting an overhual in 6.0 that should make it easier for new users

**Comment by TheComputerizer** [comment]
6.0 has been released so I am closing this
