### ISSUE TITLE
1.16.5 forge - When playing on a server, boss music plays for everyone everywhere when 1 person finds a boss.

### ISSUE THREAD

**Issue by Jetpack-Cat** [TheComputerizer/Music-Triggers#69]
1.16.5 forge
When 1 person on a server runs into a boss using the boss trigger, the music and transition card plays/shows for every person on the server everywhere, doesn't matter how close or far you are away from the person who triggered a boss fight.

**Comment by TheComputerizer** [comment]
Noted this will be resolved in 6.0

**Comment by TheComputerizer** [comment]
This has been fixed
