### ISSUE TITLE
Going outside of the mob detection range of a music trigger crashes the game

### ISSUE THREAD

**Issue by RobertHDPotatoes** [TheComputerizer/Music-Triggers#7]
Minecraft Version: 1.16.5
Forge Version: 36.2.22
Music Triggers version: 4.1

Issue: Whenever I go further than the set detection range for my mob music trigger, the game seems to reload all sounds (multiple times?) and the game permanently freezes and must be manually closed and restarted. Unfortunately my log file probably won't provide much help because of the nature of this type of crash, but I'll supply it anyway just in case.

Latest Log: https://pastebin.com/RLYFRG9G

These are the only changes in my config file (musictriggers.txt) and they work fine as long as you don't go outside the 64 block range for detection.

Songs=<
Wither,1,withering,64,400,200
Swampjaw,1,swampjaw,64,400,200
>

musictriggers.txt pastebin just in case you want it: https://pastebin.com/8TqS5YVF

**Comment by RobertHDPotatoes** [comment]
So after a little bit more testing, it seems to happen pretty consistently if you are able to move outside of the range *very* quickly. It's possible this may not happen under 99% of circumstances. In this example, I stood next to a wither as it spawned (I have a mod that modifies explosion strength, and it blasted me outside the detection range in under a second) and it crashed right after, while I zoomed in on where I was just at. Another time it crashed when I flew away at top speed in creative, but that seems to happen rarely.
![image](https://user-images.githubusercontent.com/72235443/150698808-3edba3eb-a8f6-453b-b0da-4a1ee6278031.png)

**Comment by TheComputerizer** [comment]
Alright thanks for reporting, I will take a look

**Comment by RobertHDPotatoes** [comment]
Apologies, I didn't realize that the key for reloading sounds overlapped with my zoom key and that's what was actually causing the crash. As I was the one who was causing the issue, I will be closing this because it's a non-issue
