### ISSUE TITLE
[Forge 1.18.2 -- 6.0 EX] Including a Fade Out parameter prevents transitions from happening

### ISSUE THREAD

**Issue by Manan6619** [TheComputerizer/Music-Triggers#70]
Inclusion of a _Fade Out_ parameter on a trigger prevents said trigger from being transitioned to. Instead, the currently active trigger will have a brief spike in volume, but continue playing. Upon returning to the trigger that didn't have a _Fade out_ parameter, it will start one of its songs from the beginning, even if that trigger's song was already (erroneously) playing.

Reloading Music Triggers while in a trigger that includes a _Fade Out_ parameter will allow it to play properly until it is no longer active/isn't the highest priority, and the bug comes back into effect.

**To Reproduce**
1. Create two triggers that are easy to go back and forth between(e.g. for two different biomes).
2. Include a _Fade Out_ time for one of the biomes.
3. Travel back and forth in between the biomes **(beware of loud volume spikes!)**.

**Comment by TheComputerizer** [comment]
closing this here as 6.0 betas are currently limited to the discord server
