### ISSUE TITLE
[1.12.2-5.4] "Dead" Trigger with "Time" Property restarts song on respawning

### ISSUE THREAD

**Issue by poombus** [TheComputerizer/Music-Triggers#71]
**Describe the bug**
Setting the time property on the "dead" trigger restarts the song when the player respawns. 
I would the expect the song to continue for the value set after respawning. Instead, it replays the song from the beginning and stops after the value set by "time."

**To Reproduce**
```
[song1]
   [song1.trigger]
      name="dead"
      priority="1"
      time="100"
```

Dying will play the song as expected, but respawning will restart the song.

**Additional context**
Forge 1.12.2 Mod Version 5.4

**Comment by TheComputerizer** [comment]
This should be fixed in 6.0
