### ISSUE TITLE
[6.0 Beta] Crash upon opening GUI

### ISSUE THREAD

**Issue by Sweed-Le-Deedly** [TheComputerizer/Music-Triggers#75]
So, already found an issue when just trying to start this mod. As soon as I press the keybind to open the new GUI, the game instantly crashes. 
This is true for any key that I rebind it to and is reproducable every time. 
There are no incompatabilities that are causing this as I am only working with Music Trigger and the Impossible Library just to get a feel for it.

Here's the crash log I got from this:
[crash-2023-01-05_11.24.12-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/10353877/crash-2023-01-05_11.24.12-client.txt)

**Comment by Sweed-Le-Deedly** [comment]
Fix already found: Mod does not function with music turned off.

**Comment by TheComputerizer** [comment]
Noted

**Comment by TheComputerizer** [comment]
Looks like this crash only happens when the main config file for a channel is empty which is basically what you already figured out. It will be fixed for the release

**Comment by TheComputerizer** [comment]
This has been fixed in 6.0
