### ISSUE TITLE
[6.0 Beta] Crash when trying to add a new song to the redirect file from GUI.

### ISSUE THREAD

**Issue by CorleFulmon** [TheComputerizer/Music-Triggers#76]
When trying to add a new song to the redirect config file by using the in game music triggers GUI, the game crashes.

This issue occurs when editing the redirect.txt file of the config by using the music triggers GUI. When pressing the "Add linked song" button, it tries to add a blank song and then crashes.

Crash log:
[crash-2023-01-05_20.18.28-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/10355143/crash-2023-01-05_20.18.28-client.txt)

**Comment by TheComputerizer** [comment]
Yeah the new GUI is bound to have some issues at the moment. This has been noted

**Comment by TheComputerizer** [comment]
This has been fixed in 6.0
