### ISSUE TITLE
[1.19.2] GUI issues

### ISSUE THREAD

**Issue by PlayerRager** [TheComputerizer/Music-Triggers#77]
When looking through triggers, I couldn’t scroll through it, when typing, space inputs null, and you can’t hold shift or ctrl while typing.

**Comment by TheComputerizer** [comment]
Thanks for the report, this will be fixed for the release version

**Comment by PlayerRager** [comment]
Awesome! Also I came across another issue, I don’t know if I’m doing something wrong but the Universal Parameters, at least the fade out trigger, doesn’t save.

**Comment by PlayerRager** [comment]
Here’s a list of other issues I came across for now
Crashes when putting no value in volume pitch
Universal Parameters don’t save
GUI crashes without the preset you provided
Fades don’t work, debug menu shows fades working but doesn’t actually fade

**Comment by TheComputerizer** [comment]
This has been fixed in 6.0
