### ISSUE TITLE
[1.16.5-6.0 Beta] Mutiple triggers on one priority breaks the mod past the title screen

### ISSUE THREAD

**Issue by zackFlame2** [TheComputerizer/Music-Triggers#78]
### Bug Description
Having multiple triggers on one priority (due to identifiers, in this case) causes the whole thing to break after loading into a world, along with a bunch of StackOverflow errors.

**Additional context**
Here's the log excerpt, in case you need to look over it again:
https://pastebin.com/5BagmVs4

**Comment by TheComputerizer** [comment]
Noted, this will be fixed for release

**Comment by TheComputerizer** [comment]
This has been fixed in 6.0
