### ISSUE TITLE
1.19.2 fabric (6.0 BETA) all parameters need to be in quotations

### ISSUE THREAD

**Issue by McWendigoes** [TheComputerizer/Music-Triggers#79]
If you don't encapsulate all your parameters in quotations, your game will crash.

To replicate this bug, don't encapsulate parameters in quotations, for example boolean values, number integers and values.

Mod using: MusicTriggers 1.19.2 fabric (6.0 beta)

**Comment by TheComputerizer** [comment]
Noted this will be addressed by the release version

**Comment by TheComputerizer** [comment]
This has been fixed in 6.0
