### ISSUE TITLE
[1.12.2] Game crashes upon initialization

### ISSUE THREAD

**Issue by SlytherTheUndertaker** [TheComputerizer/Music-Triggers#84]
I'm not sure why that happened, it just crashed once I installed it and started the game. Here's a crash report:
https://pastebin.com/fc8Rerhg

**Comment by SlytherTheUndertaker** [comment]
UPDATE: No matter how much I've tried to sort out my mods, it keeps crashing. :/
I really hope this gets fixed.

**Comment by TheComputerizer** [comment]
soontm

**Comment by TheComputerizer** [comment]
This has been fixed in 6.0
