### ISSUE TITLE
[Fabric - 1.19.2 - 6.0 BETA] Music is not fading in or out/Mob trigger not functioning

### ISSUE THREAD

**Issue by GentlemenDuck** [TheComputerizer/Music-Triggers#85]
**Describe the bug**
To put it simply, whenever I attempt to assign an integer above 4 to fade_in/fade_out it will refuse to stop playing even when the trigger has already ended, even playing during the menu. When I assign 4 or lower however, the song does stop, but it will STOP. There is no fade out or fade in; it will either abruptly end or begin. Another issue I have is that whenever I try to assign a track to a mob, it will refuse to play. I've tried doing everything from assigning: MOB. To assigning a mob ID, but no matter what I assign. It just refuses to play. 

**To Reproduce**
I've listed the steps above.

**Additional context**
The mod is fantastic, and I really want to see it skyrocket, but I feel like it needs to be more consumer friendly and it needs more polish. Again, I'm not sure if it's a bug or it's just me, but one thing's clear: I can't get it working. I would really appreciate it if you could aid me in this issue. Thanks.

**Comment by TheComputerizer** [comment]
Yeah the beta has a lot of issues. The release version for 6.0 should be ready pretty soon though

**Comment by GentlemenDuck** [comment]
> Yeah the beta has a lot of issues. The release version for 6.0 should be ready pretty soon though

Ohh, alrighty then. Well, in that case; I wish you the best in developing this wonderful mod. Thanks for letting me know.

**Comment by TheComputerizer** [comment]
This has been fixed in 6.0
