### ISSUE TITLE
What I've found so far

### ISSUE THREAD

**Issue by Failtronic2** [TheComputerizer/Music-Triggers#87]
VERSION: 1.19.2 Forge
OTHER MODS: Biomes O' Plenty, JourneyMap, Nature's Compass

- Clicking on delete mode does nothing in every menu, meaning the only way to delete something is to manually remove it from the main.toml.

- Sometimes after editing multiple text fields, the most recently edited text will appear in every field interacted with. (example: priority and identifier, add priority number, edit identifier, find out priority now also contains identifier's text)

- Clicking on playback information instantly crashes the game if you have no songs at all.

- Noticeable audio stutter when a lot of chunks load and on the menu song when it starts after leaving a world. (likely normal)

- Pressing reset song and skip song opens the log visualizer, and does not reset or skip the song, meaning the only way to reset or skip a song is to use reload configurations.

- Playback information doesn't show the name of the current playing song and the time is odd. The left number counts up like it is supposed to, but the right number which is the track's length appears to be set to the maximum value, regardless of the song.

- Clicking the button in the center of playback info with no song playing caused a crash.

- Time trigger is odd and not working the way I would think it should. Even when outside of the trigger's specified time (in this case, daytime trigger when it is nighttime), no song plays at all despite meeting the conditions of the biome and night trigger. Then when switching to day, the day song won't play either. I think what is happening is if the other songs' priorities are lower, the day trigger seems to ALWAYS wait for daytime and not allow anything else to happen, even if it is nighttime, therefore not letting a night song play, and vice versa. This occurs even if I remove the night trigger, all day songs do not play if there is a night trigger of any priority even if said night trigger is attached to no songs.
  - Trigger set to play at all times of day gets overwritten by day and night triggers, no matter the priority of the day and night triggers
  - Setting the all times trigger to be a higher priority than the day and night triggers caused both to not play, even though the all trigger is only on one song and the day and night are on their own songs
  - After deleting all the time triggers and restarting the game, the first trigger to play is now playing everywhere including when in the MT GUI, paused, during loading screens, and on the main menu. After deleting an all biomes trigger (which was not attached to the song) and restarting the game, it was corrected.

- Sometimes making a change to, removing, or adding a trigger causes none to play, forcing you to completely restart the game.

- Saved several changes at once while looking at the main.toml file. GUI saved 2 changes onto the same line. (check_above_level = "true180") Likely has to do with the aforementioned typing in multiple fields thing.

- Audio pauses if Minecraft isn't focused. (Game wasn't paused, likely normal)

**Comment by TheComputerizer** [comment]
The audio pausing when tabbed out is an intended feature and the issues with the time trigger sound like a potential configuration error, but I would need to see the config file for context.

All the issues with the playback screen are due to the fact that it has not yet been implemented

**Comment by TheComputerizer** [comment]
Most if not all of these should be fixed in 6.1
