### ISSUE TITLE
[6.0 Release 1.19.2] Search Bar in "Add Sound Resource" Not working

### ISSUE THREAD

**Issue by Spenz0r** [TheComputerizer/Music-Triggers#88]
I can't click on the search bar at the top of the list of vanilla sound files.
I'm on the Fabric 1.19.2 version.

To reproduce:
Open GUI>Channel Music>Redirect>Add Sound Resource>Try to use the search bar at the top

**Comment by Spenz0r** [comment]
Clicking "Delete Mode" also does nothing

**Comment by TheComputerizer** [comment]
Confirmed, this will be fixed soontm

**Comment by TheComputerizer** [comment]
Fixed in 6.1
