### ISSUE TITLE
[Fabric 1.19.2-fabric-6.0] Crash when using menu.

### ISSUE THREAD

**Issue by pokesmells** [TheComputerizer/Music-Triggers#89]
**Describe the bug**
Opened the GUi for music triggers and clicked a button, then got served with a client side crash 😭
**To Reproduce**
1. Install the mod
2. Open the GUI
3. Crash when using the GUI.

**Additional context**
https://mclo.gs/OK68l01 - Crash Logs
https://mclo.gs/ksoRnnv - Latest Logs, should include mods.

**Comment by TheComputerizer** [comment]
Duplicate of #87 - The playback screen is currently unimplemented
