### ISSUE TITLE
[1.18.2 6.0 Release Crash]

### ISSUE THREAD

**Issue by 0BLIQU3** [TheComputerizer/Music-Triggers#90]
**Describe the bug**
Start-up crash: Upon running this mod alongside the Pyrotastic mod, Minecraft crashes upon start-up.

**To Reproduce**
1. Download latest version of Pyrotastic
2. Download latest version of Music Triggers and The Impossible Library
3. Start Minecraft
4. Crash

**Additional context**
[crash-2023-03-09_18.30.17-client.txt](https://github.com/TheComputerizer/Music-Triggers/files/10937422/crash-2023-03-09_18.30.17-client.txt)

**Comment by TheComputerizer** [comment]
From what I can tell, this seems like an issue with Pyrotastic since the error is related to the creation of the firework model. I will leave the issue open for now though just in case. If you have a full log it might give more information

**Comment by TheComputerizer** [comment]
Since #91 also had a crash that looks the same with a different mod, _some_ kind of weird interaction is going on and at the moment I am not too sure where it is happening yet.

Are both Illuminations and Pyrotastic able to be run at the same time by themselves?

Also a stated above a full log with one of the crashes (ideally on forge) would probably be able to clear things up a bit better

**Comment by 0BLIQU3** [comment]
Sorry for the late response.
Here's the latest.log for a crash with Pyrotastic.
[latest.log](https://github.com/TheComputerizer/Music-Triggers/files/10983325/latest.log)
Here's the latest.log for a crash with Illuminations.
[latest.log](https://github.com/TheComputerizer/Music-Triggers/files/10983285/latest.log)

Yes, Illuminations and Pyrotastic can run by themselves at the same time.

**Comment by TheComputerizer** [comment]
Do you have a `channel.toml` file in your MusicTriggers config? If not, can you try making one and seeing if it still crashes?

**Comment by 0BLIQU3** [comment]
There is already a channels.toml file present in the config.

**Comment by TheComputerizer** [comment]
I'm guessing it was an issue of dependency shading, but either way it's been fixed in dev and will also be fixed in 6.1

**Comment by TheComputerizer** [comment]
Fixed in 6.1
