### ISSUE TITLE
[1.16.5] Server crash

### ISSUE THREAD

**Issue by SpetsnazUS** [TheComputerizer/Music-Triggers#92]
**Describe the bug**
Server crashes upon launch stating, "java.lang.RuntimeException: Attempted to load class net/minecraft/client/world/ClientWorld for invalid dist DEDICATED_SERVER"

**To Reproduce**
Start a server with the mod and library installed.

**Additional context**
[crash-2023-03-10_18.56.06-fml.txt](https://github.com/TheComputerizer/Music-Triggers/files/10945155/crash-2023-03-10_18.56.06-fml.txt)

**Comment by TheComputerizer** [comment]
Confirmed, 6.0 seems to not work on servers for all versions past 1.12.2 at the moment

**Comment by TheComputerizer** [comment]
Fixed in 6.1
