### ISSUE TITLE
[1.16.5 Forge] Valkyrien Skies/Eureka! Airships!

### ISSUE THREAD

**Issue by Sazuzaki** [TheComputerizer/Music-Triggers#93]
**Describe the bug**
Installing Music Triggers makes the mod fail to load.

**Additional Information**
Probably something to do with the UI. I know it crashes with Shoulder Surfing because of player raytrace or something like that. I'm reporting this cause this mod is amazing, and I would love to have both mods installed at the same time

**Latest Log**
https://pastebin.com/mr4Je0v6

**Comment by TheComputerizer** [comment]
Seems like Valkyrien Skies is shading the same dependency that Music Triggers is, which causes forge to break since the same classpath tried to be injected twice. Basically, its something that I can fix on my end, but the Valkyrien Skies devs could also fix it on their end

**Comment by Sazuzaki** [comment]
Thanks for explaining! Ultimately I chose your mod over Valkyrien Skies, cause boss fights without music just kinda suck. I hope it isn't too hard of a fix though, cause it certainly is a really damn cool mod.

6.0 has been awesome and hopefully the next patch comes soon. Good work!

**Comment by TheComputerizer** [comment]
Fixed in 6.1
