### ISSUE TITLE
[6.0 - 1.19.2 - Fabric] Trigger Combinations not working properly

### ISSUE THREAD

**Issue by Huetete** [TheComputerizer/Music-Triggers#94]
Triggers only meant for a combination will each have its priority effecting, when the combination conditions aren't met, any other triggers that has lower priority.

An example to reproduce. You just combine any trigger like height, with `check_above_level = true`, with any biome trigger. The height trigger must have higher priority. If you go anywhere outside that specific biome from the combination you won't hear any biome song.

**Comment by TheComputerizer** [comment]
Confirmed

**Comment by TheComputerizer** [comment]
Fixed in 6.1
