### ISSUE TITLE
[6.0 - 1.19.2 - Fabric] Mob Targeting & MOB tag

### ISSUE THREAD

**Issue by Huetete** [TheComputerizer/Music-Triggers#95]
Simply the `mob_targeting` parameter is broken.
The entry `MOB` for `resource_name` will extend to passive mobs and not only for hostile creatures.

**Comment by TheComputerizer** [comment]
Confirmed, this will be fixed in 6.1

**Comment by TheComputerizer** [comment]
Fixed in 6.1
