### ISSUE TITLE
[6.0 - 1.19.2 - General] Raid Trigger probably doesn't work

### ISSUE THREAD

**Issue by Huetete** [TheComputerizer/Music-Triggers#97]
Raid Trigger won't appear in the GUI. Then, regardless if you write all the formula manually in the main config, setting up the trigger and linking it into a song pool won't do anything or play any music. Also it won't show up in the playable triggers when a raid occurs.

Note: I apologize for the wrong label.

**Comment by TheComputerizer** [comment]
Confirmed, this will be fixed in 6.1

**Comment by TheComputerizer** [comment]
Fixed in 6.1
