### ISSUE TITLE
[1.16.5] MusicTriggers 6.1 - just_once=2 not working

### ISSUE THREAD

**Issue by sfiomn** [TheComputerizer/Music-Triggers#99]
I've this simple main.toml:

[triggers]
	[[triggers.season]]
		identifier = "spring"
		level = "0"
		priority = "2"
		fade_in = "80"
		
[songs]
	[songs.season2_spring]
		triggers = [ "dimension-overworld" "season-spring" ]
		play_once = "2"

When I'm in the overworld, the song is played in a loop, and the fading isn't taken into account after the first iteration of the song.

**Comment by sfiomn** [comment]
Of course, the spacing is correct on my side, looks like github formatting put everything on the left.

And it's doubled square brackets because I've multiple season triggers, but the behaviour is for everyone.

**Comment by TheComputerizer** [comment]
This has been fixed in 6.2
